import About from '@/components/about'
import Navbar from '@/components/navbar'
import Main from '@/components/main'
import Head from 'next/head'
import Skills from '@/components/skills'
import Projects from '@/components/projects'
import Contact from '@/components/contact'


export default function Home() {
  return (
    <>
      <Head>
        <title>Nicole Selig | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Main/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact/>
    </>
  )
}
